2023-11-03 18:48:18,612 Using proactor: IocpProactor
2023-11-03 18:48:18,631 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 18:48:18,910 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 18:48:18,913 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:56> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 67, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 18:49:35,983 Using proactor: IocpProactor
2023-11-03 18:49:35,994 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 18:49:36,177 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 18:49:36,180 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:56> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 67, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 18:53:37,145 Using proactor: IocpProactor
2023-11-03 18:53:37,155 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 18:53:37,358 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 18:53:37,361 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:56> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 67, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 19:29:23,510 Using proactor: IocpProactor
2023-11-03 19:29:23,521 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 19:29:23,924 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 19:29:23,925 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:65> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 76, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 19:31:07,174 Using proactor: IocpProactor
2023-11-03 19:31:07,185 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 19:31:09,805 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 19:31:09,807 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:67> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 78, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 19:33:55,786 Using proactor: IocpProactor
2023-11-03 19:33:55,795 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 19:33:55,993 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 19:33:55,994 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:68> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 79, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 19:34:20,689 Using proactor: IocpProactor
2023-11-03 19:34:20,697 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 19:34:20,894 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 19:34:20,895 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:68> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 79, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 20:45:44,287 Using proactor: IocpProactor
2023-11-03 20:45:44,307 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 20:45:44,579 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 20:45:44,583 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:97> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 108, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 20:49:50,142 Using proactor: IocpProactor
2023-11-03 20:49:50,158 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 20:49:50,419 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 20:49:50,423 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:99> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 110, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 20:50:45,915 Using proactor: IocpProactor
2023-11-03 20:50:45,925 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 20:50:46,114 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 20:50:46,115 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:99> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 110, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 21:02:59,814 Using proactor: IocpProactor
2023-11-03 21:02:59,828 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 21:03:00,263 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 21:03:00,264 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:99> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 110, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 21:03:40,974 Using proactor: IocpProactor
2023-11-03 21:03:40,988 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 21:03:41,377 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 21:03:41,378 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:99> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 110, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 21:04:35,477 Using proactor: IocpProactor
2023-11-03 21:04:35,490 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 21:04:35,872 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 21:04:35,873 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:99> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 110, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 21:05:53,274 Using proactor: IocpProactor
2023-11-03 21:05:53,302 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 21:05:53,723 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 21:05:53,724 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:99> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 110, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 22:01:39,265 Using proactor: IocpProactor
2023-11-03 22:01:39,289 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 22:01:39,739 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 22:01:39,743 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:100> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 111, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 22:03:13,811 Using proactor: IocpProactor
2023-11-03 22:03:13,820 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 22:03:14,253 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 22:03:14,255 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:100> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 111, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:10:23,325 Using proactor: IocpProactor
2023-11-03 23:10:23,343 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:10:23,664 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 23:10:23,670 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:119> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 130, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:16:16,139 Using proactor: IocpProactor
2023-11-03 23:16:16,150 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:16:16,421 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 23:16:16,424 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:119> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 130, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:22:12,610 Using proactor: IocpProactor
2023-11-03 23:22:12,624 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:22:12,897 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 23:22:12,901 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:119> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 130, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:23:18,904 Using proactor: IocpProactor
2023-11-03 23:23:18,928 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:23:21,917 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 23:23:21,921 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:119> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 130, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:26:17,836 Using proactor: IocpProactor
2023-11-03 23:26:17,855 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:26:18,273 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=15FE6RMB2ACMZUXP HTTP/1.1" 200 None
2023-11-03 23:26:18,276 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:119> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 130, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:34:35,361 Using proactor: IocpProactor
2023-11-03 23:35:48,489 Using proactor: IocpProactor
2023-11-03 23:35:48,502 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:35:48,876 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=None HTTP/1.1" 200 None
2023-11-03 23:35:48,879 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:119> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 130, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:36:23,862 Using proactor: IocpProactor
2023-11-03 23:36:23,873 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:36:24,083 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=None HTTP/1.1" 200 None
2023-11-03 23:36:24,084 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:119> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 130, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:41:30,298 Using proactor: IocpProactor
2023-11-03 23:41:30,312 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:41:30,527 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=None HTTP/1.1" 200 None
2023-11-03 23:41:30,531 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:119> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 130, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:41:52,812 Using proactor: IocpProactor
2023-11-03 23:41:52,823 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:41:53,020 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=None HTTP/1.1" 200 None
2023-11-03 23:41:53,021 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:119> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 130, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:42:25,003 Using proactor: IocpProactor
2023-11-03 23:42:25,018 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:42:25,220 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=None HTTP/1.1" 200 None
2023-11-03 23:42:25,221 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:120> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 131, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-03 23:44:04,649 Using proactor: IocpProactor
2023-11-03 23:44:04,662 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:44:07,549 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:121> exception=SystemExit(0)>
Traceback (most recent call last):
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 125, in getData
    r = requests.get(f'https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency={Assets[i]}&to_currency=USD&apikey={APIKEY}')
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\benja\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 138, in signal_handeler
    sys.exit(0)
SystemExit: 0
2023-11-03 23:44:27,941 Using proactor: IocpProactor
2023-11-03 23:44:27,952 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-03 23:44:28,318 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=None HTTP/1.1" 200 None
2023-11-03 23:44:28,319 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:121> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 132, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-04 00:40:49,222 Using proactor: IocpProactor
2023-11-04 00:40:49,231 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-04 00:40:49,423 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=None HTTP/1.1" 200 None
2023-11-04 00:40:49,428 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:135> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 147, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
2023-11-04 01:31:43,219 Using proactor: IocpProactor
2023-11-04 01:31:43,227 Starting new HTTPS connection (1): www.alphavantage.co:443
2023-11-04 01:31:43,603 https://www.alphavantage.co:443 "GET /query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=None HTTP/1.1" 200 None
2023-11-04 01:31:43,606 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<getData() done, defined at c:\Users\benja\Desktop\Stock tracker\src\main.py:152> exception=AttributeError("'dict' object has no attribute 'Information'")>
Traceback (most recent call last):
  File "c:\Users\benja\Desktop\Stock tracker\src\main.py", line 165, in getData
    if(clean.Information == dailyLimitReached):
AttributeError: 'dict' object has no attribute 'Information'
